CREATE SEQUENCE S_APP_FUNCTION INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_APP_ROLE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_APP_TIPS INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_APP_USER INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_APPOINTMENT INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCH_DISPATCH INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCH_FLOW_CONF INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCH_FOND INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCH_HASTEN INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCH_REC_TYPE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCH_REC_USER INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCH_ROLL INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCH_TEMPLATE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCHIVES INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCHIVES_ATTEND INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCHIVES_DEP INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCHIVES_DOC INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCHIVES_HANDLE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ARCHIVES_TYPE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ASSETS_TYPE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_BOARD_TYPE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_BOARDROOM INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_BOOK INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_BOOK_BOR_RET INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_BOOK_SN INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_BOOK_TYPE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_BORROW_FILE_LIST INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_BORROW_RECORD INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CALENDAR_PLAN INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CAR INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CAR_APPLY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CART_REPAIR INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_COMPANY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CONF_ATTEND INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CONF_PRIVILEGE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CONF_SUMMARY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CONTRACT INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CONTRACT_CONFIG INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CUS_CONNECTION INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CUS_LINKMAN INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CUSTOMER INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DEP_USERS INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DEPARTMENT INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DEPRE_RECORD INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DEPRE_TYPE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DIARY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DICTIONARY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DOC_FOLDER INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DOC_HISTORY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DOC_PRIVILEGE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DOCUMENT INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DOWNLOAD_LOG INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DUTY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DUTY_REGISTER INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DUTY_SECTION INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_DUTY_SYSTEM INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_EMP_PROFILE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ERRANDS_REGISTER INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_FIELD_RIGHTS INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_FILE_ATTACH INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_FIXED_ASSETS INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_FORM_DEF INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_FORM_DEF_MAPPING INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_FORM_FIELD INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_FORM_TABLE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_FORM_TEMPLATE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_FUN_URL INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_GLOBAL_TYPE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_GOODS_APPLY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_HIRE_ISSUE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_HOLIDAY_RECORD INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_IN_MESSAGE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_IN_STOCK INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_INDEX_DISPLAY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_JOB INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_JOB_CHANGE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_LEADER_READ INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_MAIL INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_MAIL_BOX INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_MAIL_FOLDER INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_MEETING INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_MEETING_ATTEND INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_NEWS INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_NEWS_COMMENT INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_OFFICE_GOODS INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_OFFICE_GOODS_TYPE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_OUT_MAIL INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_OUT_MAIL_FOLDER INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_OUT_MAIL_USER_SETING INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PAINT_TEMPLATE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PHONE_BOOK INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PHONE_GROUP INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PLAN_ATTEND INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PRO_DEF_RIGHTS INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PRO_DEFINITION INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PRO_HANDLE_COMP INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PRO_USER_ASSIGN INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PROCESS_FORM INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PROCESS_MODULE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PROCESS_RUN INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PRODUCT INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PROJECT INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_PROVIDER INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_REGION INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_REGULATION INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_RELATIVE_JOB INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_RELATIVE_USER INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_REPORT_PARAM INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_REPORT_TEMPLATE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_RESUME INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ROLL_FILE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_ROLL_FILE_LIST INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_RUN_DATA INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_SALARY_ITEM INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_SALARY_PAYOFF INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_SALES_DETAIL INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_SALES_ORDER INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_SEAL INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_SECTION INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_SHORT_MESSAGE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_SMS_HISTORY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_SMS_MOBILE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_STAND_SALARY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_STAND_SALARY_ITEM INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_SUGGEST_BOX INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_SYS_CONFIG INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_TASK_SIGN INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_TASK_SIGN_DATA INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_TYPE_KEY INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_USER_JOB INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_USER_SUB INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_WF_GENERAL INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_WORK_PLAN INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE S_CONFERENCE INCREMENT BY 1 START WITH 10000 NOMAXVALUE MINVALUE 1 CACHE 20 NOORDER NOCYCLE;
