CREATE TABLE GOVERNMENT_INVENTORY
(
	ID BIGINT(15) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	GOVERNMENT_INVENTORY_TYPE VARCHAR(10),
	PROJECT_CLASS_LEVEL_1_NUM VARCHAR(20),
	PROJECT_CLASS_LEVEL_2_NUM VARCHAR(20),
	PROJECT_NUM VARCHAR(20),
	PROJECT_NAME VARCHAR(40),
	PROJECT_NAME_FEATURE VARCHAR(300),
	UNIT VARCHAR(10),
	AMOUNT NUMERIC(8,2),
	DETAIL VARCHAR(200),
	COMMENTS VARCHAR(100)
)DEFAULT CHARSET=UTF8;


delete from GOVERNMENT_INVENTORY


select count(*) from GOVERNMENT_QUOTA
select count(*) from GOVERNMENT_INVENTORY