CREATE PROCEDURE dbo.g4_prc_demo
     @prm_myname varchar(50),
     @prm_number1 decimal,
     @prm_number2 decimal,
     @prm_sum decimal output,
     @prm_result varchar(100) output,
     @prm_AppCode varchar(3) output,
     @prm_ErrorMsg varchar(100) output
    as
    begin
       set @prm_sum = @prm_number1 + @prm_number2;
       set @prm_result = 'hello, ' +  @prm_myname +  '!';
       set @prm_AppCode = 1;
       set @prm_ErrorMsg = 'ok';
    end
GO
CREATE TABLE [dbo].[EA_DEMO_BYJSB] (
[SXH] nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[DWMC] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[GRBM] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[XM] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[XB] nvarchar(3) COLLATE Chinese_PRC_CI_AS NULL ,
[XNL] decimal(14) NULL ,
[FYZE] decimal(14) NULL ,
[ZFJE] decimal(14) NULL ,
[YBBX] decimal(14) NULL ,
[JSSJ] datetime NULL ,
[YYMC] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[JBR] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EA_DEMO_BYJSB__1920BF5C] PRIMARY KEY ([SXH])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EA_DEMO_BYMXB] (
[SXH] nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[XH] nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[ZFLB] nvarchar(10) COLLATE Chinese_PRC_CI_AS NULL ,
[GRBM] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[XM] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[SFDLMC] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[SFXMMC] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[SL] decimal(14) NULL ,
[SJJG] decimal(14) NULL ,
[FYZE] decimal(14) NULL ,
[CD] nvarchar(128) COLLATE Chinese_PRC_CI_AS NULL ,
[GG] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[SFSJ] datetime NULL ,
[SFY] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EA_DEMO_BYMXB__1A14E395] PRIMARY KEY ([XH], [SXH])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EA_DEMO_CHINAAREA] (
[AREACODE] nvarchar(12) COLLATE Chinese_PRC_CI_AS NULL ,
[AREANAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL 
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EA_DEMO_FCF] (
[NAME] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[VALUE] nvarchar(10) COLLATE Chinese_PRC_CI_AS NULL ,
[COLOR] nvarchar(10) COLLATE Chinese_PRC_CI_AS NULL ,
[ALPHA] nvarchar(10) COLLATE Chinese_PRC_CI_AS NULL ,
[ISSLICED] nvarchar(1) COLLATE Chinese_PRC_CI_AS NULL ,
[PRODUCT] nvarchar(1) COLLATE Chinese_PRC_CI_AS NULL ,
[FCFID] decimal(14) NOT NULL ,
CONSTRAINT [PK__EA_DEMO_FCF__1B0907CE] PRIMARY KEY ([FCFID])
)
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_PRODUCT_03317E3D] ON [dbo].[EA_DEMO_FCF]
([PRODUCT] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EA_DEMO_SFXM] (
[XMID] nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[SFDLBM] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[XMMC] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[XMRJ] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[GG] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[DW] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[ZFBL] real NULL ,
[JX] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[CD] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[QYBZ] nvarchar(3) COLLATE Chinese_PRC_CI_AS NULL ,
[YYBM] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[GGSJ] datetime NULL ,
CONSTRAINT [PK__EA_DEMO_SFXM__1BFD2C07] PRIMARY KEY ([XMID])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EA_DEMO_UPLOAD] (
[FILEID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[TITLE] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[PATH] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[FILESIZE] decimal(14) NULL ,
[REMARK] nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EA_DEMO_UPLOAD__1CF15040] PRIMARY KEY ([FILEID])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EACODE] (
[FIELD] nvarchar(15) COLLATE Chinese_PRC_CI_AS NULL ,
[FIELDNAME] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[CODE] nvarchar(10) COLLATE Chinese_PRC_CI_AS NULL ,
[CODEDESC] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[ENABLED] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[EDITMODE] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[SORTNO] int NULL ,
[REMARK] nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL ,
[CODEID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
CONSTRAINT [PK__EACODE__1ED998B2] PRIMARY KEY ([CODEID]),
CONSTRAINT [INDEX_EACODE] UNIQUE ([FIELD] ASC, [CODE] ASC)
)
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_ENABLED_060DEAE8] ON [dbo].[EACODE]
([ENABLED] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_FIELDNAME_060DEAE8] ON [dbo].[EACODE]
([FIELDNAME] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_CODEDESC_060DEAE8] ON [dbo].[EACODE]
([CODEDESC] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EADEPT] (
[DEPTID] nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[DEPTNAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[PARENTID] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[CUSTOMID] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[SORTNO] int NULL ,
[LEAF] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[REMARK] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[ENABLED] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EADEPT__20C1E124] PRIMARY KEY ([DEPTID])
)
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_ENABLED_07020F21] ON [dbo].[EADEPT]
([ENABLED] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_PARENTID_07020F21] ON [dbo].[EADEPT]
([PARENTID] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAEVENT] (
[EVENTID] nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[USERID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[ACCOUNT] nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL ,
[USERNAME] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[DESCRIPTION] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[ACTIVETIME] decimal(14) NULL ,
[REQUESTPATH] nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL ,
[METHODNAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[COSTTIME] decimal(14) NULL ,
CONSTRAINT [PK__EAEVENT__21B6055D] PRIMARY KEY ([EVENTID])
)
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_ACTIVETIME_07F6335A] ON [dbo].[EAEVENT]
([ACTIVETIME] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAEXCEPTION] (
[EXCEPTIONID] nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[CLAZZ] nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL ,
[METHODNAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[EXCEPTION] ntext COLLATE Chinese_PRC_CI_AS NULL ,
[ACTIVETIME] decimal(14) NULL ,
CONSTRAINT [PK__EAEXCEPTION__22AA2996] PRIMARY KEY ([EXCEPTIONID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAHELP] (
[HELPID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[MENUID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[CONTENT] ntext COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAHELP__239E4DCF] PRIMARY KEY ([HELPID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAHTTPSESSION] (
[SESSIONID] nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[USERNAME] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[ACCOUNT] nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL ,
[CREATETIME] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[LOGINIP] nvarchar(15) COLLATE Chinese_PRC_CI_AS NULL ,
[USERID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[EXPLORER] nvarchar(15) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAHTTPSESSION__24927208] PRIMARY KEY ([SESSIONID])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAICON] (
[ICONID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[FILENAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[CSSNAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAICON__25869641] PRIMARY KEY ([ICONID])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAJDBCMONITOR] (
[MONITORID] int NOT NULL IDENTITY(1,1) ,
[SQLTEXT] ntext COLLATE Chinese_PRC_CI_AS NULL ,
[STARTTIME] decimal(14) NULL ,
[COSTTIME] decimal(14) NULL ,
[EFFECTROWS] decimal(14) NULL ,
[TYPE] nvarchar(1) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAJDBCMONITOR__286302EC] PRIMARY KEY ([MONITORID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

DBCC CHECKIDENT(N'[dbo].[EAJDBCMONITOR]', RESEED, 945)
GO

CREATE INDEX [_WA_Sys_MONITORID_0CBAE877] ON [dbo].[EAJDBCMONITOR]
([MONITORID] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_STARTTIME_276EDEB3] ON [dbo].[EAJDBCMONITOR]
([STARTTIME] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_COSTTIME_276EDEB3] ON [dbo].[EAJDBCMONITOR]
([COSTTIME] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_EFFECTROWS_276EDEB3] ON [dbo].[EAJDBCMONITOR]
([EFFECTROWS] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_TYPE_276EDEB3] ON [dbo].[EAJDBCMONITOR]
([TYPE] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAMENU] (
[MENUID] nvarchar(60) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[MENUNAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[PARENTID] nvarchar(60) COLLATE Chinese_PRC_CI_AS NULL ,
[ICONCLS] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[EXPANDED] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[REQUEST] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[LEAF] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[SORTNO] decimal(8) NULL ,
[REMARK] nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL ,
[ICON] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[MENUTYPE] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAMENU__29572725] PRIMARY KEY ([MENUID])
)
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_MENUTYPE_0DAF0CB0] ON [dbo].[EAMENU]
([MENUTYPE] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_PARENTID_0DAF0CB0] ON [dbo].[EAMENU]
([PARENTID] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAMENUPART] (
[PARTID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[MENUID] nvarchar(60) COLLATE Chinese_PRC_CI_AS NULL ,
[CMPID] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[CMPTYPE] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[REMARK] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAMENUPART__2A4B4B5E] PRIMARY KEY ([PARTID])
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAPARAM] (
[PARAMID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[PARAMKEY] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[PARAMVALUE] ntext COLLATE Chinese_PRC_CI_AS NULL ,
[REMARK] nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAPARAM__2B3F6F97] PRIMARY KEY ([PARAMID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAROLE] (
[ROLEID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[ROLENAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[DEPTID] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[ROLETYPE] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[REMARK] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[LOCKED] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAROLE__2C3393D0] PRIMARY KEY ([ROLEID])
)
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_DEPTID_108B795B] ON [dbo].[EAROLE]
([DEPTID] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_ROLETYPE_108B795B] ON [dbo].[EAROLE]
([ROLETYPE] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAROLEAUTHORIZE] (
[ROLEID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[MENUID] nvarchar(60) COLLATE Chinese_PRC_CI_AS NULL ,
[AUTHORIZELEVEL] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[AUTHORIZEID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
CONSTRAINT [PK__EAROLEAUTHORIZE__2D27B809] PRIMARY KEY ([AUTHORIZEID])
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [UK_EARWAUTHORIZE] ON [dbo].[EAROLEAUTHORIZE]
([ROLEID] ASC, [MENUID] ASC, [AUTHORIZELEVEL] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_AUTHORIZELEVEL_117F9D94] ON [dbo].[EAROLEAUTHORIZE]
([AUTHORIZELEVEL] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_MENUID_117F9D94] ON [dbo].[EAROLEAUTHORIZE]
([MENUID] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAROLEMENUPART] (
[AUTHORIZEID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[ROLEID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[MENUID] nvarchar(60) COLLATE Chinese_PRC_CI_AS NULL ,
[PARTID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[PARTAUTHTYPE] nvarchar(1) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAROLEMENUPART__2E1BDC42] PRIMARY KEY ([AUTHORIZEID])
)
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_MENUID_1273C1CD] ON [dbo].[EAROLEMENUPART]
([MENUID] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_ROLEID_1273C1CD] ON [dbo].[EAROLEMENUPART]
([ROLEID] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_PARTID_1273C1CD] ON [dbo].[EAROLEMENUPART]
([PARTID] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EASEQUENCE] (
[SEQUENCEID] nvarchar(4) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[FIELDNAME] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[MAXID] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[REMARK] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[PATTERN] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[IDTYPE] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EASEQUENCE__2F10007B] PRIMARY KEY ([SEQUENCEID])
)
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_FIELDNAME_1367E606] ON [dbo].[EASEQUENCE]
([FIELDNAME] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAUSER] (
[USERID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[USERNAME] nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL ,
[ACCOUNT] nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL ,
[PASSWORD] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[SEX] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[DEPTID] nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL ,
[LOCKED] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[REMARK] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
[USERTYPE] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
[ENABLED] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAUSER__300424B4] PRIMARY KEY ([USERID])
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [UK_EAUSER] ON [dbo].[EAUSER]
([ACCOUNT] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_LOCKED_145C0A3F] ON [dbo].[EAUSER]
([LOCKED] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_ENABLED_145C0A3F] ON [dbo].[EAUSER]
([ENABLED] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_DEPTID_145C0A3F] ON [dbo].[EAUSER]
([DEPTID] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_USERTYPE_145C0A3F] ON [dbo].[EAUSER]
([USERTYPE] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAUSERAUTHORIZE] (
[USERID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[ROLEID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[AUTHORIZEID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
CONSTRAINT [PK__EAUSERAUTHORIZE__30F848ED] PRIMARY KEY ([AUTHORIZEID])
)
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_ROLEID_15502E78] ON [dbo].[EAUSERAUTHORIZE]
([ROLEID] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_USERID_15502E78] ON [dbo].[EAUSERAUTHORIZE]
([USERID] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAUSERMENUMAP] (
[USERID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[MENUID] nvarchar(60) COLLATE Chinese_PRC_CI_AS NULL ,
[AUTHORIZEID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[AUTHORIZELEVEL] nvarchar(2) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAUSERMENUMAP__31EC6D26] PRIMARY KEY ([AUTHORIZEID])
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [UK_EAUSERMENUMAP] ON [dbo].[EAUSERMENUMAP]
([USERID] ASC, [MENUID] ASC, [AUTHORIZELEVEL] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_MENUID_164452B1] ON [dbo].[EAUSERMENUMAP]
([MENUID] ASC) 
ON [PRIMARY]
GO

CREATE INDEX [_WA_Sys_AUTHORIZELEVEL_164452B1] ON [dbo].[EAUSERMENUMAP]
([AUTHORIZELEVEL] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAUSERMENUPART] (
[AUTHORIZEID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[USERID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[MENUID] nvarchar(60) COLLATE Chinese_PRC_CI_AS NULL ,
[PARTID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NULL ,
[PARTAUTHTYPE] nvarchar(1) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAUSERMENUPART__32E0915F] PRIMARY KEY ([AUTHORIZEID])
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [UK_EAUSERMENUPART] ON [dbo].[EAUSERMENUPART]
([USERID] ASC, [MENUID] ASC, [PARTID] ASC) 
ON [PRIMARY]
GO

CREATE TABLE [dbo].[EAUSERSUBINFO] (
[USERID] nvarchar(8) COLLATE Chinese_PRC_CI_AS NOT NULL ,
[THEME] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__EAUSERSUBINFO__33D4B598] PRIMARY KEY ([USERID])
)
ON [PRIMARY]
GO