INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(1,'公共信息平台','',0,1,1);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(2,'文件管理','',0,1,2);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(3,'工程项目管理','',0,1,3);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(4,'人力资源管理','',0,1,4);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(5,'系统管理','',0,1,5);


INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(10,'营业执照','../publicInfo/businessLicense.jsp',1,1,1);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(11,'税务登记执照','../publicInfo/taxLicense.jsp',1,1,2);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(12,'ISO文件查询','../publicInfo/schIsoList.do',1,1,3);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(13,'典型工程查询','../publicInfo/queryHistoryProject.jsp',1,1,4);

INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(20,'文件上传','../businessFile/uploadBusinessFile.jsp',2,1,1);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(21,'文件查询','../businessFile/schBusinessFileList.do',2,1,2);
 
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(30,'录入项目','../projectManage/preAddProject.do',3,1,1);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(31,'查询自己项目','../projectManage/schProjectList.do?projectInfo.queryType=1',3,1,2);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(32,'查询部门项目','../projectManage/schProjectList.do?projectInfo.queryType=2',3,1,3);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(33,'查询全部项目','../projectManage/schProjectList.do?projectInfo.queryType=3',3,1,4);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(34,'填写部门成本','',3,1,5);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(35,'删除部门奖金','',3,1,6);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(36,'填写部门成本','',3,1,7);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(37,'删除部门奖金','',3,1,8);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(38,'显示部门成本','',3,1,9);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(39,'显示部门奖金','',3,1,10);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(40,'结束项目','',3,1,11);


INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(40,'新增员工','../employeeManage/newUserInfo.do',4,1,1);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(41,'查询员工','../employeeManage/listUserInfo.do',4,1,2);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(42,'新增职务','../employeeManage/addRole.jsp',4,1,3);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(43,'查询职务','../employeeManage/listRole.do',4,1,4);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(44,'新增部门','../department/addDepartment.jsp',4,1,5);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(45,'查询部门','../department/schAdminDeptList.do',4,1,6);

INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(51,'ISO文件上传','../systemManage/uploadIsoFile.jsp',5,1,1);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(52,'发布通知','../systemManage/publishMessage.jsp',5,1,2);
INSERT INTO ADMIN_MENU (MENU_ID,MENU_NAME,MENU_URL,PARENT_MENU_ID,MENU_ENABLE,MENU_INDEX)
VALUES(53,'日志查询','../systemManage/queryLog.jsp',5,1,3);

insert into ADMIN_ROLE (ROLE_ID, ROLE_NAME, ROLE_COUNT, ROLE_REMARK) values('1','董事长','1','董事长专用');

insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','1');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','10');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','11');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','12');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','13');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','2');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','20');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','21');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','3');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','30');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','31');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','32');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','33');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','34');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','35');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','36');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','37');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','38');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','4');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','40');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','41');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','42');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','43');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','44');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','45');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','5');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','51');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','52');
insert into ROLE_MENU_RESTRACTION (`ROLE_ID`, `MENU_ID`) values('1','53');

insert into USER_INFO (`USER_ID`, `USER_REAL_NAME`, `USER_IDENTIFIER`, `USER_NAME`, `USER_SEX`, `USER_IDCARD`, `HUMEN_FILES`, `USER_BIRTHDAY`, `FAMILY_ADDRESS`, `PHONE`, `MOBILE_PHONE`, `PARTY`, `EDU_BACKGROUND`, `SCHOOL`, `MAJOR`, `EDU_COUNTINU`, `GRADUATE_DATE`, `ONBOARD_DATE`, `LEAVE_DATE`, `USER_RELATION`, `USER_STATUS`, `INSURANCE_TYPE`, `USER_REMARK`, `USER_PASSWORD`, `REGISTER_DATE`, `EMAIL`, `ROLE_ID`, `DEPT_ID`, `CERTIFICATION_ID`, `USER_TITLE`) values('1','','','chairman','0','','','0000-00-00 00:00:00','','','','','0','','','0','0000-00-00 00:00:00','0000-00-00 00:00:00','0000-00-00 00:00:00','','0','0','','e10adc3949ba59abbe56e057f20f883e','0000-00-00 00:00:00',NULL,1,NULL,NULL,'0');

insert into ROLE_USER_RESTRACTION (ROLE_ID, USER_ID) values('1','1');